### ISSUE TITLE
Error loading Gunsmith

### ISSUE THREAD

**Issue by ROKA611** [randallarms/gunsmith#38]
[09:36:09] [Server thread/ERROR]: Could not load 'plugins/GunSmith.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_12_R1/inventory/CraftItemStack
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:301) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_12_R1/inventory/CraftItemStack
	at com.kraken.gunsmith.GunSmithGUI.<clinit>(GunSmithGUI.java:12) ~[?:?]
	at com.kraken.gunsmith.GunSmith.<init>(GunSmith.java:36) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_131]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_131]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_12_R1.inventory.CraftItemStack
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
	at com.kraken.gunsmith.GunSmithGUI.<clinit>(GunSmithGUI.java:12) ~[?:?]
	at com.kraken.gunsmith.GunSmith.<init>(GunSmith.java:36) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_131]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_131]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	... 6 more

Not sure whats wrong.

**Comment by randallarms** [comment]
It says "org.bukkit.craftbukkit.v1_11_R1" -- are you running Bukkit/Spigot for Minecraft v1.11? If so, you will need to upgrade to Minecraft v1.12 to use the latest versions of GunSmith (including the GUI).

**Comment by ROKA611** [comment]
i was using 1.11.2 version and i was using your 1.12 version of your plugin.

**Comment by randallarms** [comment]
GunSmith v0.8.4+ requires a Minecraft server be updated to 1.12 with CraftBukkit or Spigot to run properly. Please update your server and try again. Let me know if there are any further issues.
